### ISSUE TITLE
Example composite.sil doesn't verify

### ISSUE THREAD

**Issue by viper-admin** [viperproject/silicon#132]
> Created by **@mschwerhoff** on 2015-02-10 13:58
> Last updated on 2015-05-26 07:52

One of Yannis' old examples, needs further investigation.

**Comment by fabiopakk** [comment]
This file doesn't seem to exist anymore in our repositories, at least in the main core and examples: silver, silicon, carbon, viperserver and example. So I'll close this issue but please reopen and report me back if that's not the case.
