### ISSUE TITLE
Remove need for a local variable from examples\list_insert_tmp.sil

### ISSUE THREAD

**Issue by viper-admin** [viperproject/silicon#191]
> Created by **@mschwerhoff** on 2015-12-03 14:52
> Last updated on 2017-11-22 08:55

Due to limitations of the current implementation of heuristics, `examples\list_insert_tmp.sil` needs to declare `var prev: Ref := crt`, which is not used in the program. However, it is needed by the heuristics because they need to have an access path to the value to which `crt` points at that line in the program.

**Comment by mschwerhoff** [comment]
Heuristics have been removed from Silicon.
