### ISSUE TITLE
Various ghost-operation-and-fractional-permission-related behaviours, in iterator example

### ISSUE THREAD

**Issue by viper-admin** [viperproject/silicon#192]
> Created by **@mschwerhoff** on 2015-12-03 14:53

The commented lines at the end of the following file show that the behaviour of a very nested sequence of ghost operations seems sensitive to various changes. Example discussed with Malte at hackathon II.

---

Attachments:
* [**`magic-wand-iterator-fails.sil`**](https://gist.githubusercontent.com/viper-admin/ffeb2dc55d20bb8e55804eb283a4f7d7/raw/a3f85ec05e93c5dbfe8134008879b74271aff5b1/magic-wand-iterator-fails.sil)

**Comment by mschwerhoff** [comment]
Not directly reproducible since the wands syntax changed. Moreover, Nils Becker provided a version with the new syntax that works.
