### ISSUE TITLE
Losing information about values of fields which are given up when a wand is applied

### ISSUE THREAD

**Issue by viper-admin** [viperproject/silicon#230]
> Created by bitbucket user **fhahn** on 2016-04-04 10:32
> Last updated on 2018-08-20 20:58

Consider the example below. The wand in `fail` asserts `r == x.f`. After applying the wand, Silicon cannot deduce `r.v == x.f.v`, hence the assertion fails.

```
#!scala
field f: Ref
field v: Int

method fail(r: Ref, x: Ref)
  requires acc(r.v) --* acc(x.f) && acc(x.f.v) && r == x.f
  requires acc(r.v) && r.v == 0
{
  apply acc(r.v) --* acc(x.f) && acc(x.f.v) && r == x.f
  assert x.f.v == 0
}
```

---

Attachments:
* [**`apply-loss-simple.sil`**](https://gist.githubusercontent.com/viper-admin/56686f24cf7b43e506d9a66f0c13233e/raw/3eb7e226fb31406d9f143204a58e2a6c6fdff067/apply-loss-simple.sil)

**Comment by mschwerhoff** [comment]
Duplicate of #304
