### ISSUE TITLE
Function axiom not available when proving function postcondition

### ISSUE THREAD

**Issue by viper-admin** [viperproject/silicon#247]
> Created by **@mschwerhoff** on 2016-09-07 07:52
> Last updated on 2017-08-09 07:14

Silicon fails to verify the following code *if* the two additional postconditions are removed:

```
#! text

field data: Int
field next: Ref

predicate lseg(this: Ref, end: Ref) {
  this != end ==>
       acc(this.data) && acc(this.next)
    && lseg(this.next, end)
    && unfolding lseg(this.next, end) in this.next != end ==> this.data <= this.next.data
}

function lsegContent(this: Ref, end: Ref): Seq[Int]
  requires lseg(this, end)
  // TWO ADDITIONAL POSTCONDITIONS
  ensures  this == end ==> result == Seq[Int]()
  ensures  this != end ==> result[0] == unfolding lseg(this, end) in this.data
  // FAILS if the previous two ensures clauses are removed
  ensures  forall i: Int, j: Int :: 0 <= i && i < j && j < |result| ==> result[i] <= result[j]
{
  this == end
    ? Seq[Int]()
    : unfolding lseg(this, end) in Seq(this.data) ++ lsegContent(this.next, end)
}

domain dummy {
  function trg(v: Int): Bool
  axiom trg_ax { forall v: Int :: trg(v) }
}
```

This (most likely) happens because the definitional function axiom is not yet available by the time the function postcondition is to be checked. It is needed, however, to conclude that `result[0] <= result[1]` (and thus also `<= result[2]` etc.).

Attention: Also be aware of [Carbon issue 155](https://github.com/viperproject/carbon/issues/155).

**Comment by mschwerhoff** [comment]
Won't fix, see discussion for [Carbon issue 155](https://github.com/viperproject/carbon/issues/155).
