### ISSUE TITLE
SymbExLogger misses states in branches with verification errors

### ISSUE THREAD

**Issue by viper-admin** [viperproject/silicon#259]
> Created by **@aterga** on 2016-11-08 10:22
> Last updated on 2019-08-27 15:56

The following example doesn't produce a state in the else branch: 

```
method foo(n:Int,b:Bool,c:Bool)
{
  if ( b ) {
     assert true
  } else {
    assert true
    assert false
  }
}
```

However, there is a state in the else brach in the following example: 

```
method foo(n:Int,b:Bool,c:Bool)
{
  if ( b ) {
     assert true
  } else {
    assert true
  }
}
```

**Comment by mschwerhoff** [comment]
Resolved with commit 85ecb641a28f0a58808528d520aaa088a2b8dbf8
