### ISSUE TITLE
Multi-phase exhaling of permissions

### ISSUE THREAD

**Issue by viper-admin** [viperproject/silicon#30]
> Created by **@mschwerhoff** on 2013-05-25 12:20
> Last updated on 2016-04-15 11:59

The multi-phase exhaling as described in the permission paper by Heule, Summers et al. is not yet implemented in Silicon. This results, for example, in the unsoundness exhibited by the unexpectedly sucessful test case `t2b` in `Sil:all/basic/fresh.sil`.

**Comment by gauravpartha** [comment]
In a recent Viper meeting, we decided to stop the multi-phase exhale for Carbon and to expect that exhales should always be executing from left-to-right. Carbon has been updated correspondingly (https://github.com/viperproject/carbon/pull/411) and the Silver test suite as well (https://github.com/viperproject/silver/pull/573)

@mschwerhoff: So, I guess we can close this issue?

**Comment by mschwerhoff** [comment]
@gauravpartha  I'm happily closing this issue :-)
