### ISSUE TITLE
State consolidation not reliably triggered inside magic wand proof code

### ISSUE THREAD

**Issue by viper-admin** [viperproject/silicon#309]
> Created by **@vakaras** on 2017-11-14 14:22

See lines 83-85. The precondition of `itemAt` on line 85 is expected to fail.

Silicon version: `Silicon 1.1-SNAPSHOT (<https://github.com/viperproject/silicon/commit/f2370a98ed1e6c40cb32d1579971b0acd59988f5>)`

---

Attachments:
* [**`test.sil`**](https://gist.githubusercontent.com/viper-admin/e503e141d931037415f5477c5801f118/raw/56212a4b32d2a79cc0ab327d19e418e59e069918/test.sil)

**Comment by mschwerhoff** [comment]
No longer reproducible: the precondition of `itemAt` on line 85 now fails as expected.
