### ISSUE TITLE
Incompleteness with non-linear arithmetic, but only when using predicates

### ISSUE THREAD

**Issue by viper-admin** [viperproject/silicon#367]
> Created by **@fpoli** on 2019-02-01 16:45
> Last updated on 2019-11-04 16:30

I found that in the following program an assertion does not hold, but only in the case where there are predicates involved.

Is this just because of incompleteness of non-linear arithmetic in Z3, or is there some other issue regarding triggers?

```silicon
field val: Int

// Note the `false` precondition
function unreachable(): Bool requires false 

// A definition that i32 multiplication will not under/overflow
function safe_mult_i32(x: Int, y: Int): Bool
  requires -2147483648 <= x && x <= 2147483647
  requires -2147483648 <= y && y <= 2147483647
{
  (-9223372036854775808 <= x * y && x * y <= 9223372036854775807)
  ? (-2147483648 <= x * y && x * y <= 2147483647)
  // The following is correctly proven to be unreachable
  : unreachable()
}

predicate i32(self: Ref) {
  acc(self.val) && -2147483648 <= self.val && self.val <= 2147483647
}

// First, the following method verifies fine
method test_without_predicates()
{
  var x1: Int
  var y1: Int

  inhale -2147483648 <= x1 && x1 <= 2147483647
  inhale -2147483648 <= y1 && y1 <= 2147483647

  inhale safe_mult_i32(x1, y1)

  // The following verifies
  assert -2147483648 <= x1 * y1 && x1 * y1 <= 2147483647
}

// Now the analogous, but using predicates
method test_with_predicates()
{
  var x2: Ref
  var y2: Ref

  inhale i32(x2)
  inhale i32(y2)
  unfold i32(x2)
  unfold i32(y2)

  inhale safe_mult_i32(x2.val, y2.val)

  // Why the following fails? Triggers?
  assert -2147483648 <= x2.val * y2.val && x2.val * y2.val <= 2147483647
}
```

---

Attachments:
* [**`minimal.smt2`**](https://gist.githubusercontent.com/viper-admin/f86d3afc8211f2034fc96f0fb2b09bd0/raw/98eafcaed476512a08f623289fa51a4b78182ec8/minimal.smt2)
* [**`logfile-08-good.smt2`**](https://gist.githubusercontent.com/viper-admin/f86d3afc8211f2034fc96f0fb2b09bd0/raw/ecad9917a827449fb7cd594fba5bf13693e6ae09/logfile-08-good.smt2)
* [**`logfile-08-bad.smt2`**](https://gist.githubusercontent.com/viper-admin/f86d3afc8211f2034fc96f0fb2b09bd0/raw/a6eab723420de9b1caf9ee7d9f0650e379f1c57d/logfile-08-bad.smt2)

**Comment by mschwerhoff** [comment]
Potentially related: #479, #480, #481

**Comment by mschwerhoff** [comment]
Cannot reproduce this, with latest Silicon and Z3 4.8.7.
