### ISSUE TITLE
Unsoundness: a heap dependent function is instantiated even when its precondition does not hold

### ISSUE THREAD

**Issue by viper-admin** [viperproject/silicon#376]
> Created by **@vakaras** on 2019-05-06 11:48
> Last updated on 2019-05-08 09:13

The following example verifies in Silicon while it should not:

```
function Void$discriminant(self: Ref): Int
  requires acc(Void(self))
  ensures false
{
  unfolding acc(Void(self)) in 8
}

predicate Void(self: Ref) {
  false
}

method m_void$$unreachable$opensqu$0$closesqu$() returns (_0: Ref)
{
  assert false
}
```

**Comment by mschwerhoff** [comment]
Following up on the comment from [May 8, 2019](https://github.com/viperproject/silicon/issues/376#issuecomment-588993370): To allow recursive invocations, the dummy trigger would have to be part of the function axiom body as well. Think about whether the well-definedness checks suffice here, i.e. introduce the necessary trigger.

**Comment by marcoeilers** [comment]
Finally fixed.
