### ISSUE TITLE
Incompleteness in MoreCompleteExhale

### ISSUE THREAD

**Issue by viper-admin** [viperproject/silicon#387]
> Created by **@vakaras** on 2019-06-18 16:04
> Last updated on 2019-08-28 10:36

The following example fails with `--enableMoreCompleteExhale`, but works in Carbon and in Silicon without the flag:

```
method test() {

  var _1: Ref
  var _3: Ref
  var _preserve: Ref

  inhale acc(Vec(_preserve), write-read$())
  inhale acc(usize(_3), write)
  inhale acc(_1.val_ref, read$()) && acc(Vec(_1.val_ref), read$()) && acc(usize(_3), read$())
  inhale _preserve == _1.val_ref
  inhale (unfolding acc(usize(_3), write) in _3.val_int) < len(_1.val_ref)

  assert (unfolding acc(usize(_3), write) in _3.val_int) < len(_1.val_ref)
  exhale acc(Vec(_1.val_ref), write - read$())
  assert (unfolding acc(usize(_3), write) in _3.val_int) < len(_1.val_ref)  // Fails with --enableMoreCompleteExhale

  assert  0 <= len(_1.val_ref)
}

field val_int: Int

field val_ref: Ref

function len(_pure_1: Ref): Int
  requires acc(Vec(_pure_1), read$())
  ensures 0 <= result

predicate usize(self: Ref) {
  acc(self.val_int, write)
}

function read$(): Perm
  ensures none < result
  ensures result < write

predicate Vec(self: Ref)
```

**Comment by mschwerhoff** [comment]
@vakaras @alexanderjsummers 

* https://github.com/viperproject/silicon/issues/387#issue-568261787 verifies with the most recent Silicon version, and Z3 4.8.7 x64 on Windows 10
* as does https://github.com/viperproject/silicon/issues/387#issuecomment-588993734
* as does https://github.com/viperproject/silicon/issues/387#issuecomment-588993741
* as does https://github.com/viperproject/silicon/issues/387#issuecomment-588993743
* as does https://github.com/viperproject/silicon/issues/387#issuecomment-588993754
* as does https://github.com/viperproject/silicon/issues/387#issuecomment-588993757

Let me know if you see a reason for keeping the issue open.

**Comment by vakaras** [comment]
I think it can be closed for now. I will reopen in case I find more issues.

**Comment by JonasAlaif** [comment]
@marcoeilers the following example fails with `--enableMoreCompleteExhale`, but works in Carbon and in Silicon without the flag:
```
domain ArrayDomain {}

field val_int: Int
field val_ref: Ref

function idx_into(a: ArrayDomain, a_len: Int): Int
function array_len(a: ArrayDomain): Int
function to_domain(self: Ref): ArrayDomain
  requires acc(Array(self), read$())

function read$(): Perm
  ensures none < result
  ensures result < write

predicate Array(self: Ref)
predicate usize(self: Ref) {
  acc(self.val_int, write)
}

method foo() {
  var a: Ref
  var a_len: Int
  var _3: Ref
  var unknown: Ref
  var i: Ref
  inhale acc(a.val_ref, write) && acc(Array(a.val_ref), write)

  inhale acc(_3.val_ref, write) && acc(usize(unknown), read$()) // <- removing this makes it pass

  exhale acc(a.val_ref, read$())

  inhale acc(usize(i), write) && acc(a.val_ref, read$())

  inhale (unfolding acc(usize(i), write) in
      (forall q: Int ::
        !(q < i.val_int) ||
        idx_into(to_domain(a.val_ref), q) <=
        idx_into(to_domain(a.val_ref), i.val_int)))
  assert (unfolding acc(usize(i), write) in
      (forall q: Int ::
        !(q < i.val_int) ||
        idx_into(to_domain(a.val_ref), q) <=
        idx_into(to_domain(a.val_ref), i.val_int)))
}
```
Sorry that it isn't more minimized. Adding triggers doesn't change things I think.

**Comment by mimo31** [comment]
The last example above can be further reduced to
```
field val_ref: Ref

function holds(a: Ref, b: Int): Bool

predicate p() {
  true
}

method foo() {
  var a: Ref
  var _3: Ref

  inhale acc(a.val_ref, write)

  inhale acc(_3.val_ref, write) // <- removing this makes it pass

  exhale acc(a.val_ref, 1 / 2)

  inhale acc(p(), write) && acc(a.val_ref, 1 / 2)

  inhale unfolding acc(p(), write) in (forall q: Int :: holds(a.val_ref, q))
  assert unfolding acc(p(), write) in (forall q: Int :: holds(a.val_ref, q)) // "Assert might fail." here
}
```
This doesn't verify in Silicon with `--enableMoreCompleteExhale`, but it verifies successfully in Carbon or in Silicon without the flag.

As per the comment in the code, removing one of the `inhale`s makes it work even with the flag. Alternatively, removing the exhale of `acc(a.val_ref, 1 / 2)` together with the subsequent inhale of `acc(a.val_ref, 1 / 2)` also makes it verify with the flag.

**Comment by mimo31** [comment]
The current example can be reduced even further to
```
field val: Bool

method foo() {
  var a: Ref
  var b: Ref

  inhale acc(a.val, write)

  inhale acc(b.val, write) // <- removing this makes it pass

  exhale acc(a.val, 1 / 42) // <- (alternatively) removing this also makes it pass

  assume forall q: Int :: a.val
  assert forall q: Int :: a.val // "Assert might fail." here
}
```
The behavior (of Carbon and Silicon with/without flag) is the same as in my last comment.

**Comment by marcoeilers** [comment]
Now that last one also works. I'll close it again until someone finds a new incomplete example.
