### ISSUE TITLE
Z3 4.8.6 nightly exhausts memory on issues/carbon/0210.sil — matching loop?

### ISSUE THREAD

**Issue by viper-admin** [viperproject/silicon#397]
> Created by **@mschwerhoff** on 2019-08-01 10:50
> Last updated on 2019-08-01 11:18

Using a Jenkins build of Z3 revision bec38f2, Z3 very quickly runs out of memory, at least on my home laptop. When using release Z3 4.8.4., this does not happen.

To do:

* Use axiom profiler to find out if there is a matching loop
* Determine who is to blame if there is a matching loop: the example or Silicon’s encoding

**Comment by fabiopakk** [comment]
I cannot reproduce this issue as the current version of Silicon runs properly on this example. There is, however, a possible explanation: the issue's description mentions that the current version of Z3 is bec38f2, but in reality our build server is using 78ed71b8d which is more modern and has bug fixes.
