### ISSUE TITLE
Insufficient permission to access field of predicate with rd() permission

### ISSUE THREAD

**Issue by fpoli** [viperproject/silicon#480]
The following does not verify, but I expect it to verify:
```
field f: Int

function rd(): Perm
    ensures result > 0/1
    ensures result < 1/1

predicate F(self: Ref) {
    acc(self.f, rd())
}

method test(x: Ref)
    requires acc(F(x), rd())
{
    unfold acc(F(x), rd())
    // Carbon: Assignment might fail. There might be insufficient permission to access x.f.
    // Silicon: Assignment might fail. There might be insufficient permission to access x.f.
    var y: Int := x.f
}
```

Adding `assume rd() * rd() > 0/1` before the assignment the program verifies.

Related:
* https://github.com/viperproject/carbon/issues/350
* #479

**Comment by fpoli** [comment]
Smaller example:
```
function rd(): Perm
    ensures result > 0/1

method test() {
    // Assert might fail. Assertion rd() * rd() > 0 / 1 might not hold.
    assert rd() * rd() > 0/1
}
```

**Comment by fpoli** [comment]
This Boogie program does not verify:
```
procedure test(x: real) returns ()
{
    assume x > 0.0;
    assert x * x > 0.0;
}
```
Z3's output is
```
unknown
(:reason-unknown "smt tactic failed to show goal to be sat/unsat (incomplete (theory arithmetic))")
(labels)
```
So, it seems that it's indeed an incompleteness of Z3.

Interestingly, by modifying the `0.0` to `0.00000000000001`, or by replacing the `>` with `>=`, Boogie and Z3 are able to verify the program.

**Comment by mschwerhoff** [comment]
Potentially related: #367, #479, #481

**Comment by fpoli** [comment]
I asked about the "smt tactic failed to show goal to be sat/unsat (incomplete (theory arithmetic))" in https://github.com/Z3Prover/z3/issues/3240

**Comment by fpoli** [comment]
In my encoding I actually know which fields should become accessible after an `unfold`, so the best solution seems to assume the fact:
```
unfold acc(F(x), rd())
assume perm(x.f) > 0/1
```

Should we close this issue as `wontfix`? Or with a new label `z3-incompleteness`?

**Comment by mschwerhoff** [comment]
Closing sounds fine. I've added the `z3` label; if you like, feel free to add a second `incompleteness` label.
