### ISSUE TITLE
Null Pointer Exception when using Silicon via fromPartialCommandLineArguments

### ISSUE THREAD

**Issue by ArquintL** [viperproject/silicon#488]
Creating a Silicon instance via `Silicon.fromPartialCommandLineArguments(...)`, starting it, and then verifying a Viper AST results in a null pointer exception when accessing `Verifier.inputFile`:
https://github.com/viperproject/silicon/blob/e10a40cd604d26b3f0b1c93e32d3c7482d99ec50/src/main/scala/verifier/DefaultMasterVerifier.scala#L156

**Comment by mschwerhoff** [comment]
I'm not sure this is a bug, but rather an incorrect initialisation. Check how Silicon instances are created elsewhere:

* https://bitbucket.org/viperproject/voila/src/default/src/main/scala/viper/voila/Voila.scala
* https://github.com/viperproject/silicon/blob/e10a40cd604d26b3f0b1c93e32d3c7482d99ec50/src/main/scala/Silicon.scala
* https://github.com/viperproject/silicon/blob/e10a40cd604d26b3f0b1c93e32d3c7482d99ec50/src/test/scala/SiliconTests.scala
* https://github.com/viperproject/silicon/blob/e10a40cd604d26b3f0b1c93e32d3c7482d99ec50/src/test/scala/PortableSiliconTests.scala

**Comment by ArquintL** [comment]
Regarding your deleted comment: I'm aware of other ways and in fact Gobra currently uses Silicon like this:
```
backend = new silicon.Silicon(reporter, List("startedBy" -> s"Unit test ${this.getClass.getSimpleName}"))
backend.parseCommandLine(commandLineArguments ++ Seq("--ignoreFile", "dummy.sil"))
backend.start()
```
To me, `Silicon.fromPartialCommandLineArguments` seems like a nice solution especially regarding the dummy file.

**Comment by fpoli** [comment]
> --ignoreFile

What is this argument?

**Comment by mschwerhoff** [comment]
The Silver CLI parser requires a Viper file, which doesn't make sense if
an AST is to be verified directly, hence this option.

Am 16/04/2020 um 10:38 schrieb Federico Poli:

**Comment by ArquintL** [comment]
This disables some existence and readability checks for the provided file in Scallop. I assume this is done here, because we don't care about "dummy.sil", it does not exist at all, and we will verify a Viper AST but need to make Scallop happy

**Comment by fpoli** [comment]
Good to know, thanks. So far in Prusti we used something like
```
backend.parseCommandLine(commandLineArguments ++ Seq("dummy.sil"))
```
without `--ignoreFile`.
