### ISSUE TITLE
Failing assert after magic wand application

### ISSUE THREAD

**Issue by karenhong** [viperproject/silicon#498]
I would expect `assert forall k : Int :: k >= 0 && k < (index-1) ==> get(head, k) == old(get(head, k))` to verify but it fails to do so. 

```
field elem: Int
field next: Ref

predicate list(this: Ref) {
    acc(this.elem) && acc(this.next) && (this.next != null ==> list(this.next)) 
}

method insert(head: Ref, idx: Int)
    requires list(head)
{
    exhale list(head)
    
    var curr : Ref
    inhale list(curr)
    inhale list(curr) --* list(head) 
        && forall j : Int :: j >= idx ==> get(head, j) == old[lhs](get(curr, j - idx))
        && forall k : Int :: k >= 0 && k < idx ==> get(head, k) == old(get(head, k))

    apply list(curr) --* list(head) 
        && forall j : Int :: j >= idx ==> get(head, j) == old[lhs](get(curr, j - idx))
        && forall k : Int :: k >= 0 && k < idx ==> get(head, k) == old(get(head, k))

    assert forall k : Int :: k >= 0 && k < idx ==> get(head, k) == old(get(head, k))
}

function get(head: Ref, i: Int) : Ref
    requires acc(list(head))
```

**Comment by mschwerhoff** [comment]
It would be great if you could cut down the example as much as possible. This will make it easier to work out the root cause and thus increase the chances of the issue getting fixed soon.

**Comment by karenhong** [comment]
I updated the example and cut it down as much as I could.

**Comment by karenhong** [comment]
I realized that this example is actually invalid as there is an issue with the parentheses.  I am missing parentheses around each of the foralls resulting in the quantifiers being nested inside one another.  

Closing the issue and sorry for any inconvenience.
