### ISSUE TITLE
Order of exploration of branches

### ISSUE THREAD

**Issue by fpoli** [viperproject/silicon#501]
How does Silicon decide which branch of a CFG to check first?

In the following program we use labels and gotos to encode a CFG with two branches. We would like to encode the program such that we reliably report an error in block `second` **only if** block `first` contains no errors. Is it enough to order the gotos in block `begin` such that `goto first` is syntactically before `goto second`? Can we rely on that?

```silver
method test(b: Bool)
{
  // === begin ===
  label begin
  if (b) {
    goto first
  }
  goto second

  // === first ===
  label first
  // ... might contain an error
  goto end

  // === second ===
  label second
  assert false // Is an error reported here only if `first` has no errors?
  goto end

  // === end ===
  label end
}
```

To:@mschwerhoff @dohrau
Cc: @cmatheja

**Comment by dohrau** [comment]
The gotos actually do not introduce the branches. It is the if-statements that do.

I assume that Silicon uses the out-edges of the CFG that are computed as follows.
```
private val outEdgesMap: Map[Int, Seq[Edge[S, E]]] = edges.groupBy(_.source.id)
```
I skimmed over the CFG generation code and dare to say that `edges` somehow preserves the order of conditional edges such that the edge corresponding to the true-branch of an if-statement comes before the edge corresponding to the false-branch (this is what you need, right?).

However, I am not sure whether the `groupBy` method preserves this order. At least the documentation does not seem to promise that (to be safe, we should probably assume that it does not). I can replace this with code that guarantees to preserve the order, if you want me to - just let me know.

Moreover, I don't know how things are actually handled in Silicon.

**Comment by mschwerhoff** [comment]
If the same CFG comes in, Silicon should always explore it in the same order. I can double-check that — and fix it, if necessary — but not in the next few weeks.

More generally, though:
* When Carbon eventually supports CFGs, it will probably always explore both branches, and it is ultimately a shortcoming of Silicon that it doesn't do that as well.
* It also not obvious to me that the order in which the backends explore a program should be clearly defined.

If you need to enforce this specific behaviour, can't you do that in the frontend? If your AST had line numbers in it, you could sort and filter by those. Or add other markers in order to postprocess the error messages.

**Comment by fpoli** [comment]
> this is what you need, right?

Yep.

> If you need to enforce this specific behaviour, can't you do that in the frontend? If your AST had line numbers in it, you could sort and filter by those. Or add other markers in order to postprocess the error messages.

We already order error messages by location. The issue arises when we just have one error, let's say at line 40, then the user fixes it and suddenly the tool reports an error at line 20, and the user is confused. We can give an explanation (line 20 and 40 are on different branches...), but it would be much better if we were able to check branches in a particular order.

---

Thanks for the answers! My takeaway is that I can try to generate the branches of `if` statements such that they encode the order that we want, and Silicon will hopefully check branches in that order. At least, nothing seems to explicitly prevent it.

If it's easy, it would be nice to replace `groupby` with something that preserves the order. However, I would give a low priority to this feature.

**Comment by mschwerhoff** [comment]
@fpoli If I understand correctly, you'd like to rely on the order (and go through additional trouble) to work-around the fact that Silicon reports only one error per method — is that right?

Either way, let me know if you observe nondeterministic branch exploration in Silicon.

**Comment by fpoli** [comment]
> @fpoli If I understand correctly, you'd like to rely on the order (and go through additional trouble) to work-around the fact that Silicon reports only one error per method — is that right?

Yes. Generating `if` branches in a particular order is easy for us, and it's really nice to be able to report the verification error in the syntactically-first branch that contains errors.

I'll close this and open a new issue in case I observe nondeterministic branch exploration, sure.
