### ISSUE TITLE
"unfolding" as sequence indexing causes parser error

### ISSUE THREAD

**Issue by ArmborstL** [viperproject/silicon#504]
The following code causes a parser error "_Parse error: Expected found "]\n}", expected invalid identifier   ..._" at the closing bracket of the `assert`:
```
field lst: Seq[Bool]
field y: Int

predicate x(r: Ref) {
    acc(r.y, write)
}

method m(r: Ref)
    requires x(r)
    requires acc(r.lst, write)
{
  assert r.lst[unfolding x(r) in r.y]
}
```
Is this a bug, or is there a reason why `unfolding` is not allowed in indexing expressions?

Using a `let` avoids the parser issue (i.e. `assert let idx==(unfolding x(r) in r.y) in r.lst[idx]`).

Note that VerCors can successfully use silicon to verify such programs. So silicon seems to support this kind of expression internally, just not in the parser.

**Comment by mschwerhoff** [comment]
Thanks for reporting this! This indeed seems to be a restriction of the parser (or in the consistency checker, if we really wanted to prevent such expressions). Could you please file a [Silver issue](https://github.com/viperproject/silver/issues) and close this one?

**Comment by ArmborstL** [comment]
Issue moved to silver as https://github.com/viperproject/silver/issues/460
