### ISSUE TITLE
Z3ProverStdIO is using Java for handling I/O

### ISSUE THREAD

**Issue by fabiopakk** [viperproject/silicon#513]
The current version of Scala provides Scala.io.Source. It is perhaps a good idea to replace the current use of Java I/O for Scala I/O for uniformity and maintainability.

**Comment by fabiopakk** [comment]
This will have to wait for Scala 2.13 as only reading is possible with Scala.

**Comment by mschwerhoff** [comment]
Unclear what to replace.
