### ISSUE TITLE
Modulo is not defined consistently between silicon and carbon

### ISSUE THREAD

**Issue by bobismijnnaam** [viperproject/silicon#530]
The following code snippet seems to produce different results for different implementations of viper. The 20.07 version of carbon prefers -2, the master version of silicon prefers 1. Is this intentional, an oversight, or already fixed in the master version of carbon?

(I have not been able to get carbon working yet on my machine so I haven't tested for the master version of carbon.)

```python
method carbon_fail() {
    assert (-2 % 3) == 1;
}

method silicon_fail() {
    assert (-2 % 3) == -2;
}
```

I'm not sure which one is preferable. I was assuming the first version was the case, but the second version is a bit easier to work around using `((i % n) + n) % n`. At the very least it would be nice if this difference could be documented, since that does not seem to be the case currently.

**Comment by mschwerhoff** [comment]
Nice catch. The root cause is probably that (if I'm not mistaken) Carbon implicitly uses Boogie's default definition of modulo, whereas Silicon uses Z3's default definition.

**Comment by mschwerhoff** [comment]
Superseded by [Silver issue 297](https://github.com/viperproject/silver/issues/297)
