### ISSUE TITLE
Repeated precondition does not verify as postcondition

### ISSUE THREAD

**Issue by bobismijnnaam** [viperproject/silicon#565]
The following two methods cannot satisfy their postcondition, but I would expect them to:

```
method m1(diz: Ref, globals: Ref, i: Int)
  requires diz != null
  requires (true && forall y: Int :: i * (i + 1) <= y && y < (i + 1) * (i + 1) ==> y == i)
  ensures (forall y: Int :: i * (i + 1) <= y && y < (i + 1) * (i + 1) ==> y == i)
{ 

}

function xx(t: Int): Int
function yy(t: Int): Int

method m2(diz: Ref, globals: Ref, i: Int)
  requires diz != null
  requires (true && forall y: Int :: xx(i) <= y && y < yy(i) ==> y == i)
  ensures (forall y: Int :: xx(i) <= y && y < yy(i) ==> y == i)
{ 

}
```

At first I thought multiplication might be problematic, but in the second method there is no multiplication, and there it still fails. The examples fail on silicon master, and also for carbon master.

Also, the vscode plugin breaks for me if I remove the "true &&" in both cases: first it says there's an error at the "ensures", and then when I trigger verification again (say, by adding a space somewhere), the error moves to the "requires", even though the error is still about the postcondition. Should I add an issue for that as well, and is there a way to turn off caching?

**Comment by bobismijnnaam** [comment]
@ArmborstL figured out that the program passes by adding the identity function:

```
method m1(diz: Ref, globals: Ref, i: Int)
  requires diz != null
  requires (true && forall y: Int :: i * (i + 1) <= y && y < (i + 1) * (i + 1) ==> id(y) == i)
  ensures (forall y: Int :: i * (i + 1) <= y && y < (i + 1) * (i + 1) ==> id(y) == i)
{ 

}

function xx(t: Int): Int
function yy(t: Int): Int
function id(i: Int): Int {
    i
}

method m2(diz: Ref, globals: Ref, i: Int)
  requires diz != null
  requires (true && forall y: Int :: xx(i) <= y && y < yy(i) ==> id(y) == i)
  ensures (forall y: Int :: xx(i) <= y && y < yy(i) ==> id(y) == i)
{ 

}
```

This is enough of a workaround for me, so this issue can be closed as far as I am concerned. If there are any other ways to work around this particular case I'd be interested in hearing them, though.

**Comment by ArmborstL** [comment]
What I find curious is that Viper also says that this postcondition may not hold:
```
method m2(diz: Ref, globals: Ref, i: Int)
  requires diz != null
  requires (true && (forall y: Int :: xx(i) <= y && y < yy(i) ==> id(y) == i))
  ensures (forall y: Int :: xx(i) <= y && y < yy(i) ==> y == id(y) && y == i)
{ 

}
```
I would expect that the `id(y)` in the postcondition triggers the quantifier of the precondition, and then it could prove the postcondition. Am I missing something?

**Comment by mschwerhoff** [comment]
@bobismijnnaam This is, unfortunately, behaviour that is to be expected, due to how E-matching and triggers and SMT solver work: both quantifiers `forall y: Int :: i * (i + 1) <= y && y < (i + 1) * (i + 1) ==> y == i)` and `forall y: Int :: xx(i) <= y && y < yy(i) ==> y == i` do not contain any expressions that could be used as triggers, which makes it likely that the SMT solver never instantiates the precondition quantifier when trying to prove the postcondition. Adding the identify functions yields the subexpression `id(y)`, which is a valid trigger.

@ArmborstL That looks like an incompleteness in Silicon, I've created dedicated issue #567. Thanks for reporting.
