### ISSUE TITLE
While loop implemented with goto on a label with invariant verifies when it shouldn't.

### ISSUE THREAD

**Issue by Dspil** [viperproject/silicon#607]
This program:

```
method f() returns (i:Int, j:Int)
{
    i := 10
    j := 10
    while (i > 0)
    invariant i == j
    {
        i := i - 1
        goto X
        j := j - 1
    }
    label X
    assert i == j
}
```

does not verify failing at the assertion. If the same program though is implemented with a goto:

```
method f() returns (i:Int, j:Int)
{
    i := 10
    j := 10
    label W
    invariant i == j
    i := i - 1
    goto X
    j := j - 1
    if (i > 0) {
        goto W
    }
    label X
    assert i == j
}
```

it does not verify with carbon as backend but it verifies with silicon when it shouldn't. 
This issue might be related to [this one](https://github.com/viperproject/silicon/issues/525)

**Comment by mschwerhoff** [comment]
Comparing the CFG Silver creates for the program above with the CFG corresponding to issue #525, it seems that in both cases, the culprit is a nonsensical loop head.

![cfg2](https://user-images.githubusercontent.com/151203/161057413-ce2572a7-e910-43fd-a5c8-b3cd777d0e95.png)

**Comment by marcoeilers** [comment]
Actually fixed now in https://github.com/viperproject/silver/pull/859.
