### ISSUE TITLE
java.util.concurrent.ExecutionException for quantified wand not injective

### ISSUE THREAD

**Issue by fpoli** [viperproject/silicon#615]
The following program makes Silicon raise a Java exception instead of reporting a verification error.

```
predicate T()
predicate U(x: Ref)

method lemma()
    requires forall b: Bool :: T() --* (forall x: Ref :: U(x)) 
```

```
java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Quantified wand not injective
```

**Comment by mschwerhoff** [comment]
Resolved with 05cf31074cc03625c11c84b7cd5314e66a3829a6 and [Silver commit 2f0e6ed ](https://github.com/viperproject/silver/commit/2f0e6ed70fc95e6a334867cc625933a7de816679)
