### ISSUE TITLE
NoPosition causes spaces in z3 log

### ISSUE THREAD

**Issue by bobismijnnaam** [viperproject/silicon#621]
VerCors creates (most?) silver nodes with position NoPosition. This causes a space to end up in the `:qid` of quantifiers, which in turn causes spaces to end up in the z3.log output, which causes Axiom Profiler to not parse the log, I think.

A trace of my line of thinking:
1. VerCors puts NoPosition in foralls

https://github.com/utwente-fmt/vercors/blob/e245edc6cd82248bca003d44b1902f3e9a08c24b/viper/src/main/java/viper/api/ColToSilver.scala#L233

```scala
case col.Forall(bindings, triggers, body) =>
  scoped { silver.Forall(bindings.map(variable), triggers.map(trigger), exp(body))(info=expInfo(e)) }
```

2. Method `sourceLine` produces `<no position>` if a quantifier has position `NoPosition`, and hence a space ends up in the name (Evaluator.scala, def eval2, case sourceQuant: QuantifiedExp) 

https://github.com/viperproject/silicon/blob/c3dc27c0ee860fb2672caedfd3dc01a9fa2ff3ba/src/main/scala/rules/Evaluator.scala#L619

3. The name with a space in it is assigned to a quantifier in TermToSMTLib2Converter. It seems that z3 handles the space just fine in its input. Then, the space ends up in the z3 log output, which I guess in theory could be according to spec. However, Axiom Profiler doesn't like this, and produces an error. (TermToSMTLib2Converter, def render, case Quantification)

https://github.com/viperproject/silicon/blob/c3dc27c0ee860fb2672caedfd3dc01a9fa2ff3ba/src/main/scala/decider/TermToSMTLib2Converter.scala#L142

Not sure what the best way to proceed is. Probably in VerCors we'll change quantifier generation to not use a NoPosition for quantifiers, since it's an easy and short term fix, and seems to work perfectly. Maybe in silicon the space can be removed from `<no position>` to prevent other kinds of bugs like this. Changing z3 and axiom profiler to accomodate spaces might not be worth the effort, but I've made an issue in case they do want to improve z3's logging parts a bit.

**Comment by marcoeilers** [comment]
Fixed in PR #681.
