### ISSUE TITLE
Z3 regression in 4.8.10

### ISSUE THREAD

**Issue by fpoli** [viperproject/silicon#664]
Are we aware of any regression in Z3 version 4.8.10? As reported [here](https://github.com/viperproject/prusti-dev/issues/1245), it seems that Z3 version 4.8.8 is much faster on a program.

**Comment by marcoeilers** [comment]
The reason we're still on 4.8.7 is that every newer Z3 version leads to worse performance either on a few select examples or across the board. That's true for Silicon and Carbon, and apparently Dafny and Boogie have the same problem (and are also still on similar versions as we are).

Generally, at the moment, anyone using Viper should use 4.8.7.

**Comment by fpoli** [comment]
Thanks. I didn't notice that Viper ships 4.8.7.
